# Generated by Django 4.1.9 on 2023-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="beds",
            field=models.PositiveIntegerField(default=0, verbose_name="Beds"),
        ),
    ]
