# Generated by Django 4.1.9 on 2023-05-19 03:50

from django.db import migrations, models
import ehms.articles.models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_content_alter_article_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ehms.articles.models.article_image_upload,
                verbose_name="Article Image",
            ),
        ),
    ]
