# Generated by Django 4.1.9 on 2023-05-19 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
    ]
