# Generated by Django 4.1.9 on 2023-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_sessions", "0003_ward_practitioners"),
        ("practitioners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practitioner",
            name="wards",
            field=models.ManyToManyField(to="medical_sessions.ward"),
        ),
    ]
