# Generated by Django 4.1.9 on 2023-05-16 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("practitioners", "0002_practitioner_wards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practitioner",
            name="wards",
        ),
    ]
