# Generated by Django 4.1.9 on 2023-05-15 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Region or county", "verbose_name_plural": "Regions or counties"},
        ),
        migrations.AlterModelOptions(
            name="town",
            options={"verbose_name": "Town or City", "verbose_name_plural": "Towns or Cities"},
        ),
    ]
