# Generated by Django 4.1.9 on 2023-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_alter_region_options_alter_town_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="uid",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID"),
        ),
        migrations.AddField(
            model_name="district",
            name="uid",
            field=models.CharField(blank=True, max_length=255, verbose_name="UID"),
        ),
        migrations.AddField(
            model_name="postcode",
            name="uid",
            field=models.CharField(blank=True, max_length=255, verbose_name="UID"),
        ),
        migrations.AddField(
            model_name="region",
            name="uid",
            field=models.CharField(blank=True, max_length=255, verbose_name="UID"),
        ),
        migrations.AddField(
            model_name="town",
            name="uid",
            field=models.CharField(blank=True, max_length=255, verbose_name="UID"),
        ),
    ]
