# Generated by Django 4.1.9 on 2023-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0003_country_uid_district_uid_postcode_uid_region_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="uid",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="postcode",
            name="uid",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="region",
            name="uid",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID"),
        ),
        migrations.AlterField(
            model_name="town",
            name="uid",
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID"),
        ),
    ]
