# Generated by Django 4.1.9 on 2023-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalsession",
            name="emergency_session",
            field=models.BooleanField(default=False, verbose_name="Is this an emergency session?"),
        ),
    ]
