# Generated by Django 4.1.9 on 2023-05-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("practitioners", "0001_initial"),
        ("medical_sessions", "0002_medicalsession_emergency_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="practitioners",
            field=models.ManyToManyField(to="practitioners.practitioner"),
        ),
    ]
