# Generated by Django 4.1.9 on 2023-05-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medical_sessions", "0003_ward_practitioners"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalsession",
            name="creation_place",
            field=models.CharField(blank=True, max_length=100, verbose_name="Where it is created?"),
        ),
        migrations.AlterField(
            model_name="medicalsession",
            name="department",
            field=models.ForeignKey(
                default="OPD",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="medical_session_department",
                to="medical_sessions.department",
                verbose_name="Department",
            ),
        ),
    ]
