# Generated by Django 4.1.9 on 2023-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_sessions", "0004_medicalsession_creation_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalsession",
            name="ipd_status",
            field=models.CharField(
                choices=[("Discharged", "Discharged"), ("Occupied", "Occupied"), ("Not Applicable", "Not Applicable")],
                default="Not Applicable",
                max_length=20,
                verbose_name="Patient IPD Status",
            ),
        ),
    ]
