# Generated by Django 4.1.9 on 2023-05-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_sessions", "0006_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
