# Generated by Django 4.1.9 on 2023-05-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_health_status"),
        ("medical_sessions", "0007_alter_keyword_name_alter_ward_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalsession",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="medical_session_patient",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
    ]
